version: 0.1
phases:
  install:
    commands:
      - pip3 install -r requirements.txt -t cam_trigger/build
      - cp cam_trigger/cam_trigger.py cam_trigger/build
      - pip3 install -r requirements.txt -t picture_results/build
      - cp picture_results/picture_results.py picture_results/build
      - pip3 install -r requirements.txt -t rekognition_skill/build
      - cp rekognition_skill/rekognition_skill.py rekognition_skill/build
      - aws cloudformation package --template-file template.yaml --s3-bucket iot-rekognition-demo-eu-west-1
                                   --output-template-file template-output.yaml
      
artifacts:
  type: zip
  files:
    - template.yaml
    - template-output.yaml