AWSTemplateFormatVersion: '2010-09-09'
Description: 'iot_mirror

  Demo of Greengrass Iot PiCam and Rekognition

  '
Globals:
  Function:
    AutoPublishAlias: live
    DeploymentPreference:
      Type: AllAtOnce
    Timeout: 5
Outputs:
  ApigwURL:
    Description: API Gateway endpoint URL for Prod environment for First Function
    Value:
      Fn::Sub: https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/trigger
  CamTrigger:
    Description: CamTrigger Function ARN
    Value:
      Fn::GetAtt:
      - CamTrigger
      - Arn
  PictureTaker:
    Description: PictureTaker Function ARN
    Value:
      Fn::GetAtt:
      - PictureTaker
      - Arn
Resources:
  CamTrigger:
    Properties:
      CodeUri: s3://iot-mirror-eu-central-1/a7df558ec98c0c28785e98bc8f6ae7f8
      Environment:
        Variables:
          PARAM1: VALUE
      Events:
        Api:
          Properties:
            Method: GET
            Path: /trigger
          Type: Api
      Handler: cam_trigger.lambda_handler
      Policies:
      - Statement:
        - Action:
          - iot:Publish
          - iot:GetThingShadow
          Effect: Allow
          Resource: '*'
        Version: '2012-10-17'
      Runtime: python3.6
      Tracing: Active
    Type: AWS::Serverless::Function
  PictureResults:
    Properties:
      CodeUri: s3://iot-mirror-eu-central-1/d25c732dd9fccf09444611e131f87bb7
      Environment:
        Variables:
          PARAM1: VALUE
      Events:
        Api:
          Properties:
            Method: GET
            Path: /results
          Type: Api
      Handler: picture_results.lambda_handler
      Policies:
      - Statement:
        - Action:
          - iot:Publish
          - iot:GetThingShadow
          Effect: Allow
          Resource: '*'
        Version: '2012-10-17'
      Runtime: python3.6
      Tracing: Active
    Type: AWS::Serverless::Function
  PictureTaker:
    Properties:
      CodeUri: s3://iot-mirror-eu-central-1/cb42e91e51a5e64c8e4a5961ddeaf467
      Handler: picture_taker.lambda_handler
      Runtime: python2.7
      Timeout: 60
      Tracing: Active
    Type: AWS::Serverless::Function
Transform: AWS::Serverless-2016-10-31
