version: 0.1
phases:
  install:
    commands:
      - pip3 install -r rekognition_skill/requirements.txt -t rekognition_skill/build
      - cp rekognition_skill/rekognition_skill.py rekognition_skill/build
      - aws cloudformation package --template-file rekognition_skill/skill_template.yaml --s3-bucket iot-rekognition-demo-eu-west-1
                                   --output-template-file template-output.yaml
      
artifacts:
  type: zip
  files:
    - template.yaml
    - template-output.yaml